/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author NANDO
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    public JButton getSignIn() {
        return SignIn;
    }

    public JButton getSignUp() {
        return SignUp;
    }

    public JPasswordField getFieldPassword() {
        return FieldPassword;
    }

    public JTextField getFieldUsername() {
        return FieldUsername;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dasar = new javax.swing.JPanel();
        HalamanLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FieldUsername = new javax.swing.JTextField();
        FieldPassword = new javax.swing.JPasswordField();
        SignIn = new javax.swing.JButton();
        SignUp = new javax.swing.JButton();
        HalamanSignUpAs = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SignUpDosen = new javax.swing.JButton();
        SignUpMahasiswa = new javax.swing.JButton();
        HalamanSignUpDosen = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        NIPDosen = new javax.swing.JTextField();
        KodeDosen = new javax.swing.JTextField();
        NamaDosen = new javax.swing.JTextField();
        UmurDosen = new javax.swing.JTextField();
        AlamatDosen = new javax.swing.JTextField();
        UsernameDosen = new javax.swing.JTextField();
        CreateAkunDosen = new javax.swing.JButton();
        CancelCreateAkunDosen = new javax.swing.JButton();
        PasswordAkunDosen = new javax.swing.JPasswordField();
        HalamanSignUpMahasiswa = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        NIMMahasiswa = new javax.swing.JTextField();
        NamaMahasiswa = new javax.swing.JTextField();
        UmurMahasiswa = new javax.swing.JTextField();
        AlamatMahasiswa = new javax.swing.JTextField();
        UsernameMahasiswa = new javax.swing.JTextField();
        CreateAkunMahasiswa = new javax.swing.JButton();
        CancelCreateAkunMahasiswa = new javax.swing.JButton();
        PasswordAkunMahasiswa = new javax.swing.JPasswordField();
        MenuDosen = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        addMahasiswa = new javax.swing.JButton();
        createTugas = new javax.swing.JButton();
        deletMahasiswa = new javax.swing.JButton();
        createKelas = new javax.swing.JButton();
        LogoutDosen = new javax.swing.JButton();
        HalamanCreateKelas = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        NamaMatkul = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        NamaKelas = new javax.swing.JTextField();
        CreateKelas = new javax.swing.JButton();
        CancelKelas = new javax.swing.JButton();
        HalamanCreateTugas = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        NamaTugas = new javax.swing.JTextField();
        PilihNamaMatkul = new javax.swing.JComboBox<>();
        DeadlineTugas = new javax.swing.JTextField();
        CreateTugas = new javax.swing.JButton();
        CancelTugas = new javax.swing.JButton();
        HalamanAddMahasiswa = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        PilihKelas = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        addNamaMahasiswa = new javax.swing.JTextField();
        addNimMahasiswa = new javax.swing.JTextField();
        addMahasiswaKeKelas = new javax.swing.JButton();
        cancelMahasiswaKeKelas = new javax.swing.JButton();
        HalamanDeleteMahasiswa = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        PilihKelasDeleteMahasiswa = new javax.swing.JComboBox<>();
        PilihMahasiswaDeleteMahasiswa = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        DeleteMahasiswa = new javax.swing.JButton();
        CancelDeleteMahasiswa = new javax.swing.JButton();
        HalamanViewDaftarKelas = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        ListNamaKelas = new javax.swing.JScrollPane();
        ListDaftarKelas = new javax.swing.JList<>();
        BackViewDaftarKelas = new javax.swing.JButton();
        HalamanJoinKelas = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        JoinKelas = new javax.swing.JButton();
        CancelJoinKelas = new javax.swing.JButton();
        ListNamaDosen = new javax.swing.JComboBox<>();
        ListKelasJoinKelas = new javax.swing.JComboBox<>();
        MenuMahasiswa = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        LogoutMahasiswa = new javax.swing.JButton();
        LihatDaftarKelas = new javax.swing.JButton();
        JoinKelasMenuMahasiswa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dasar.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("E-Learning");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Password");

        FieldUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        FieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldUsernameActionPerformed(evt);
            }
        });

        FieldPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        SignIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SignIn.setText("Sign In");
        SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInActionPerformed(evt);
            }
        });

        SignUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SignUp.setText("Sign Up");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HalamanLoginLayout = new javax.swing.GroupLayout(HalamanLogin);
        HalamanLogin.setLayout(HalamanLoginLayout);
        HalamanLoginLayout.setHorizontalGroup(
            HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanLoginLayout.createSequentialGroup()
                .addGroup(HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HalamanLoginLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel2))
                    .addGroup(HalamanLoginLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addGroup(HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(HalamanLoginLayout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(SignIn)
                                    .addGap(88, 88, 88)
                                    .addComponent(SignUp))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanLoginLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(HalamanLoginLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(113, 113, 113)
                                .addComponent(FieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        HalamanLoginLayout.setVerticalGroup(
            HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanLoginLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addGroup(HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(50, 50, 50)
                .addGroup(HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignIn)
                    .addComponent(SignUp))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        dasar.add(HalamanLogin, "HalamanLogin");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("E-Learning");

        SignUpDosen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SignUpDosen.setText("Dosen");
        SignUpDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpDosenActionPerformed(evt);
            }
        });

        SignUpMahasiswa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SignUpMahasiswa.setText("Mahasiswa");

        javax.swing.GroupLayout HalamanSignUpAsLayout = new javax.swing.GroupLayout(HalamanSignUpAs);
        HalamanSignUpAs.setLayout(HalamanSignUpAsLayout);
        HalamanSignUpAsLayout.setHorizontalGroup(
            HalamanSignUpAsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanSignUpAsLayout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanSignUpAsLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(SignUpDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(SignUpMahasiswa)
                .addGap(230, 230, 230))
        );
        HalamanSignUpAsLayout.setVerticalGroup(
            HalamanSignUpAsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanSignUpAsLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel4)
                .addGap(113, 113, 113)
                .addGroup(HalamanSignUpAsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignUpMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignUpDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        dasar.add(HalamanSignUpAs, "HalamanSignUpAs");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("E-Learning");

        jLabel6.setText("Nama");

        jLabel7.setText("NIP");

        jLabel8.setText("Umur");

        jLabel9.setText("Kode Dosen");

        jLabel10.setText("Alamat");

        jLabel11.setText("Username");

        jLabel12.setText("Password");

        AlamatDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatDosenActionPerformed(evt);
            }
        });

        CreateAkunDosen.setText("Create");

        CancelCreateAkunDosen.setText("Cancel");

        javax.swing.GroupLayout HalamanSignUpDosenLayout = new javax.swing.GroupLayout(HalamanSignUpDosen);
        HalamanSignUpDosen.setLayout(HalamanSignUpDosenLayout);
        HalamanSignUpDosenLayout.setHorizontalGroup(
            HalamanSignUpDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanSignUpDosenLayout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addGroup(HalamanSignUpDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanSignUpDosenLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(382, 382, 382))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanSignUpDosenLayout.createSequentialGroup()
                        .addGroup(HalamanSignUpDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(96, 96, 96)
                        .addGroup(HalamanSignUpDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NIPDosen)
                            .addComponent(NamaDosen, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(KodeDosen, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(UmurDosen)
                            .addComponent(AlamatDosen)
                            .addComponent(UsernameDosen)
                            .addGroup(HalamanSignUpDosenLayout.createSequentialGroup()
                                .addComponent(CreateAkunDosen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CancelCreateAkunDosen)
                                .addGap(44, 44, 44))
                            .addComponent(PasswordAkunDosen))
                        .addGap(183, 183, 183))))
        );
        HalamanSignUpDosenLayout.setVerticalGroup(
            HalamanSignUpDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanSignUpDosenLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(HalamanSignUpDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HalamanSignUpDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NIPDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HalamanSignUpDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(KodeDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HalamanSignUpDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(UmurDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(HalamanSignUpDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(AlamatDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HalamanSignUpDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(UsernameDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HalamanSignUpDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(PasswordAkunDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HalamanSignUpDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateAkunDosen)
                    .addComponent(CancelCreateAkunDosen))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        dasar.add(HalamanSignUpDosen, "HalamanSignUpDosen");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setText("E-Learning");

        jLabel14.setText("Nama");

        jLabel15.setText("NIM");

        jLabel16.setText("Umur");

        jLabel18.setText("Alamat");

        jLabel19.setText("Username");

        jLabel20.setText("Password");

        AlamatMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatMahasiswaActionPerformed(evt);
            }
        });

        CreateAkunMahasiswa.setText("Create");

        CancelCreateAkunMahasiswa.setText("Cancel");

        javax.swing.GroupLayout HalamanSignUpMahasiswaLayout = new javax.swing.GroupLayout(HalamanSignUpMahasiswa);
        HalamanSignUpMahasiswa.setLayout(HalamanSignUpMahasiswaLayout);
        HalamanSignUpMahasiswaLayout.setHorizontalGroup(
            HalamanSignUpMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanSignUpMahasiswaLayout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addGroup(HalamanSignUpMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HalamanSignUpMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanSignUpMahasiswaLayout.createSequentialGroup()
                            .addGroup(HalamanSignUpMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20))
                            .addGap(109, 109, 109)
                            .addGroup(HalamanSignUpMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NIMMahasiswa)
                                .addComponent(NamaMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                .addComponent(UmurMahasiswa)
                                .addComponent(AlamatMahasiswa)
                                .addComponent(UsernameMahasiswa)
                                .addComponent(PasswordAkunMahasiswa))
                            .addGap(183, 183, 183))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanSignUpMahasiswaLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(382, 382, 382)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanSignUpMahasiswaLayout.createSequentialGroup()
                        .addComponent(CreateAkunMahasiswa)
                        .addGap(87, 87, 87)
                        .addComponent(CancelCreateAkunMahasiswa)
                        .addGap(223, 223, 223))))
        );
        HalamanSignUpMahasiswaLayout.setVerticalGroup(
            HalamanSignUpMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanSignUpMahasiswaLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(HalamanSignUpMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(NamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HalamanSignUpMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(NIMMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HalamanSignUpMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(UmurMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HalamanSignUpMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(AlamatMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HalamanSignUpMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(UsernameMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HalamanSignUpMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(PasswordAkunMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(HalamanSignUpMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateAkunMahasiswa)
                    .addComponent(CancelCreateAkunMahasiswa))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        dasar.add(HalamanSignUpMahasiswa, "HalamanSignUpMahasiswa");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel17.setText("E-Learning");

        addMahasiswa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addMahasiswa.setText("Tambah Mahasiswa");

        createTugas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createTugas.setText("Buat Tugas");

        deletMahasiswa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deletMahasiswa.setText("Hapus Mahasiswa");

        createKelas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createKelas.setText("Buat Kelas");

        LogoutDosen.setText("Log Out");

        javax.swing.GroupLayout MenuDosenLayout = new javax.swing.GroupLayout(MenuDosen);
        MenuDosen.setLayout(MenuDosenLayout);
        MenuDosenLayout.setHorizontalGroup(
            MenuDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuDosenLayout.createSequentialGroup()
                .addGroup(MenuDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuDosenLayout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jLabel17))
                    .addGroup(MenuDosenLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(MenuDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addGroup(MenuDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletMahasiswa))))
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuDosenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LogoutDosen)
                .addGap(86, 86, 86))
        );
        MenuDosenLayout.setVerticalGroup(
            MenuDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoutDosen)
                .addGap(26, 26, 26)
                .addComponent(jLabel17)
                .addGap(80, 80, 80)
                .addGroup(MenuDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createTugas)
                    .addComponent(createKelas))
                .addGap(62, 62, 62)
                .addGroup(MenuDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMahasiswa)
                    .addComponent(deletMahasiswa))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        dasar.add(MenuDosen, "MenuDosen");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel21.setText("E-Learning");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setText("Nama Kelas");

        NamaMatkul.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setText("Nama Mata Kuliah");

        NamaKelas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        CreateKelas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CreateKelas.setText("Create");

        CancelKelas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CancelKelas.setText("Cancel");

        javax.swing.GroupLayout HalamanCreateKelasLayout = new javax.swing.GroupLayout(HalamanCreateKelas);
        HalamanCreateKelas.setLayout(HalamanCreateKelasLayout);
        HalamanCreateKelasLayout.setHorizontalGroup(
            HalamanCreateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanCreateKelasLayout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addGroup(HalamanCreateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HalamanCreateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanCreateKelasLayout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(382, 382, 382))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanCreateKelasLayout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addGap(158, 158, 158)
                            .addComponent(NamaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(213, 213, 213)))
                    .addGroup(HalamanCreateKelasLayout.createSequentialGroup()
                        .addGroup(HalamanCreateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CreateKelas)
                            .addComponent(jLabel23))
                        .addGroup(HalamanCreateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HalamanCreateKelasLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(NamaMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(HalamanCreateKelasLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(CancelKelas)))
                        .addContainerGap())))
        );
        HalamanCreateKelasLayout.setVerticalGroup(
            HalamanCreateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanCreateKelasLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel21)
                .addGap(93, 93, 93)
                .addGroup(HalamanCreateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(NamaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(HalamanCreateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(NamaMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(HalamanCreateKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateKelas)
                    .addComponent(CancelKelas))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        dasar.add(HalamanCreateKelas, "HalamanCreateKelas");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel24.setText("E-Learning");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setText("Nama Tugas");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setText("Deadline");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setText("Nama Mata Kuliah");

        NamaTugas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        PilihNamaMatkul.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PilihNamaMatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PBO", "RPL", "ASD", "BDR", "DAP" }));

        DeadlineTugas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        CreateTugas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CreateTugas.setText("Create");

        CancelTugas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CancelTugas.setText("Cancel");

        javax.swing.GroupLayout HalamanCreateTugasLayout = new javax.swing.GroupLayout(HalamanCreateTugas);
        HalamanCreateTugas.setLayout(HalamanCreateTugasLayout);
        HalamanCreateTugasLayout.setHorizontalGroup(
            HalamanCreateTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanCreateTugasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(380, 380, 380))
            .addGroup(HalamanCreateTugasLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addGroup(HalamanCreateTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(HalamanCreateTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NamaTugas)
                    .addComponent(PilihNamaMatkul, 0, 239, Short.MAX_VALUE)
                    .addComponent(DeadlineTugas))
                .addGap(196, 196, 196))
            .addGroup(HalamanCreateTugasLayout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(CreateTugas)
                .addGap(141, 141, 141)
                .addComponent(CancelTugas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HalamanCreateTugasLayout.setVerticalGroup(
            HalamanCreateTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanCreateTugasLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(HalamanCreateTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HalamanCreateTugasLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(66, 66, 66))
                    .addGroup(HalamanCreateTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NamaTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)))
                .addGap(28, 28, 28)
                .addGroup(HalamanCreateTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(PilihNamaMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(HalamanCreateTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(DeadlineTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(HalamanCreateTugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateTugas)
                    .addComponent(CancelTugas))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        dasar.add(HalamanCreateTugas, "HalamanCreateTugas");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel28.setText("E-Learning");

        PilihKelas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PilihKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IF 38-01", "IF 38-02", "IF 38-03", "IF 38-03", "IF 38-04", "IF 38-05", "IF 38-06", "IF 38-07", "IF 38-08", "IF 38-09", "IF 38-10", "IF 38-11" }));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setText("Nama Kelas");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel30.setText("Nama Mahasiswa");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel31.setText("NIM");

        addNamaMahasiswa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        addNimMahasiswa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        addMahasiswaKeKelas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addMahasiswaKeKelas.setText("Add");

        cancelMahasiswaKeKelas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelMahasiswaKeKelas.setText("Cancel");

        javax.swing.GroupLayout HalamanAddMahasiswaLayout = new javax.swing.GroupLayout(HalamanAddMahasiswa);
        HalamanAddMahasiswa.setLayout(HalamanAddMahasiswaLayout);
        HalamanAddMahasiswaLayout.setHorizontalGroup(
            HalamanAddMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanAddMahasiswaLayout.createSequentialGroup()
                .addGroup(HalamanAddMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HalamanAddMahasiswaLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addGroup(HalamanAddMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel31))
                        .addGap(147, 147, 147)
                        .addGroup(HalamanAddMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addNamaMahasiswa)
                            .addComponent(PilihKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addNimMahasiswa)))
                    .addGroup(HalamanAddMahasiswaLayout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addGroup(HalamanAddMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addGroup(HalamanAddMahasiswaLayout.createSequentialGroup()
                                .addComponent(addMahasiswaKeKelas)
                                .addGap(115, 115, 115)
                                .addComponent(cancelMahasiswaKeKelas)))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        HalamanAddMahasiswaLayout.setVerticalGroup(
            HalamanAddMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanAddMahasiswaLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel28)
                .addGap(40, 40, 40)
                .addGroup(HalamanAddMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PilihKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(41, 41, 41)
                .addGroup(HalamanAddMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(addNamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(HalamanAddMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(addNimMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(HalamanAddMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMahasiswaKeKelas)
                    .addComponent(cancelMahasiswaKeKelas))
                .addGap(39, 39, 39))
        );

        dasar.add(HalamanAddMahasiswa, "HalamanAddMahasiswa");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel32.setText("E-Learning");

        PilihKelasDeleteMahasiswa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PilihKelasDeleteMahasiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IF 38-01", "IF 38-02", "IF 38-03", "IF 38-03", "IF 38-04", "IF 38-05", "IF 38-06", "IF 38-07", "IF 38-08", "IF 38-09", "IF 38-10", "IF 38-11" }));

        PilihMahasiswaDeleteMahasiswa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PilihMahasiswaDeleteMahasiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faridh", "August", "Annisa", "Aldry", "Bagus", "Rayiemas", "Dwiki", "Cheryl", "Bety" }));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setText("Kelas");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setText("Nama Mahasiswa");

        DeleteMahasiswa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DeleteMahasiswa.setText("Delete");

        CancelDeleteMahasiswa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CancelDeleteMahasiswa.setText("Cancel");
        CancelDeleteMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelDeleteMahasiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HalamanDeleteMahasiswaLayout = new javax.swing.GroupLayout(HalamanDeleteMahasiswa);
        HalamanDeleteMahasiswa.setLayout(HalamanDeleteMahasiswaLayout);
        HalamanDeleteMahasiswaLayout.setHorizontalGroup(
            HalamanDeleteMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanDeleteMahasiswaLayout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(HalamanDeleteMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGap(121, 121, 121)
                .addGroup(HalamanDeleteMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PilihMahasiswaDeleteMahasiswa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PilihKelasDeleteMahasiswa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(269, 269, 269))
            .addGroup(HalamanDeleteMahasiswaLayout.createSequentialGroup()
                .addGroup(HalamanDeleteMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HalamanDeleteMahasiswaLayout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jLabel32))
                    .addGroup(HalamanDeleteMahasiswaLayout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(DeleteMahasiswa)
                        .addGap(94, 94, 94)
                        .addComponent(CancelDeleteMahasiswa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HalamanDeleteMahasiswaLayout.setVerticalGroup(
            HalamanDeleteMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanDeleteMahasiswaLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel32)
                .addGap(42, 42, 42)
                .addGroup(HalamanDeleteMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PilihKelasDeleteMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(39, 39, 39)
                .addGroup(HalamanDeleteMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(PilihMahasiswaDeleteMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(HalamanDeleteMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteMahasiswa)
                    .addComponent(CancelDeleteMahasiswa))
                .addGap(138, 138, 138))
        );

        dasar.add(HalamanDeleteMahasiswa, "HalamanDeleteMahasiswa");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel35.setText("E-Learning");

        ListDaftarKelas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ListDaftarKelas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "IF 38-01", "IF 38-02", "IF 38-03", "IF 38-03", "IF 38-04", "IF 38-05", "IF 38-06", "IF 38-07", "IF 38-08", "IF 38-09", "IF 38-10", "IF 38-11" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListNamaKelas.setViewportView(ListDaftarKelas);

        BackViewDaftarKelas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackViewDaftarKelas.setText("Back");
        BackViewDaftarKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackViewDaftarKelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HalamanViewDaftarKelasLayout = new javax.swing.GroupLayout(HalamanViewDaftarKelas);
        HalamanViewDaftarKelas.setLayout(HalamanViewDaftarKelasLayout);
        HalamanViewDaftarKelasLayout.setHorizontalGroup(
            HalamanViewDaftarKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanViewDaftarKelasLayout.createSequentialGroup()
                .addGroup(HalamanViewDaftarKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HalamanViewDaftarKelasLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel35))
                    .addGroup(HalamanViewDaftarKelasLayout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(ListNamaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HalamanViewDaftarKelasLayout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(BackViewDaftarKelas)))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        HalamanViewDaftarKelasLayout.setVerticalGroup(
            HalamanViewDaftarKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanViewDaftarKelasLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel35)
                .addGap(29, 29, 29)
                .addComponent(ListNamaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BackViewDaftarKelas)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        dasar.add(HalamanViewDaftarKelas, "HalamanViewDaftarKelas");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel36.setText("E-Learning");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel37.setText("Nama Dosen");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel38.setText("Nama Kelas");

        JoinKelas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JoinKelas.setText("Join");

        CancelJoinKelas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CancelJoinKelas.setText("Cancel");

        ListNamaDosen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ListNamaDosen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mamhud Dwi S", "Gia Septiani", "Aji Gautama" }));

        ListKelasJoinKelas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ListKelasJoinKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IF 38-01", "IF 38-02", "IF 38-03", "IF 38-03", "IF 38-04", "IF 38-05", "IF 38-06", "IF 38-07", "IF 38-08", "IF 38-09", "IF 38-10", "IF 38-11" }));

        javax.swing.GroupLayout HalamanJoinKelasLayout = new javax.swing.GroupLayout(HalamanJoinKelas);
        HalamanJoinKelas.setLayout(HalamanJoinKelasLayout);
        HalamanJoinKelasLayout.setHorizontalGroup(
            HalamanJoinKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanJoinKelasLayout.createSequentialGroup()
                .addGroup(HalamanJoinKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HalamanJoinKelasLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(HalamanJoinKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HalamanJoinKelasLayout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(119, 119, 119)
                                .addComponent(ListNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(HalamanJoinKelasLayout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addGap(129, 129, 129)
                                .addComponent(ListKelasJoinKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(HalamanJoinKelasLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(JoinKelas)
                                .addGap(80, 80, 80)
                                .addComponent(CancelJoinKelas))))
                    .addGroup(HalamanJoinKelasLayout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jLabel36)))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        HalamanJoinKelasLayout.setVerticalGroup(
            HalamanJoinKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanJoinKelasLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel36)
                .addGap(43, 43, 43)
                .addGroup(HalamanJoinKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(ListNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(HalamanJoinKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(ListKelasJoinKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(HalamanJoinKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JoinKelas)
                    .addComponent(CancelJoinKelas))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        dasar.add(HalamanJoinKelas, "HalamanJoinKelas");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel39.setText("E-Learning");

        LogoutMahasiswa.setText("Log Out");

        LihatDaftarKelas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LihatDaftarKelas.setText("Lihat Daftar Kelas");

        JoinKelasMenuMahasiswa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JoinKelasMenuMahasiswa.setText("Join Kelas");

        javax.swing.GroupLayout MenuMahasiswaLayout = new javax.swing.GroupLayout(MenuMahasiswa);
        MenuMahasiswa.setLayout(MenuMahasiswaLayout);
        MenuMahasiswaLayout.setHorizontalGroup(
            MenuMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuMahasiswaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutMahasiswa)
                .addGap(101, 101, 101))
            .addGroup(MenuMahasiswaLayout.createSequentialGroup()
                .addGroup(MenuMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuMahasiswaLayout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jLabel39))
                    .addGroup(MenuMahasiswaLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(LihatDaftarKelas)
                        .addGap(94, 94, 94)
                        .addComponent(JoinKelasMenuMahasiswa)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        MenuMahasiswaLayout.setVerticalGroup(
            MenuMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuMahasiswaLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(LogoutMahasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel39)
                .addGap(131, 131, 131)
                .addGroup(MenuMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LihatDaftarKelas)
                    .addComponent(JoinKelasMenuMahasiswa))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        dasar.add(MenuMahasiswa, "MenuMahasiswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 283, Short.MAX_VALUE)
                .addComponent(dasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 582, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(dasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 267, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldUsernameActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpActionPerformed

    private void SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignInActionPerformed

    private void SignUpDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpDosenActionPerformed

    private void AlamatDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatDosenActionPerformed

    private void AlamatMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatMahasiswaActionPerformed

    private void CancelDeleteMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelDeleteMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelDeleteMahasiswaActionPerformed

    private void BackViewDaftarKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackViewDaftarKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackViewDaftarKelasActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void showMessage(String pesan) {
        JOptionPane.showMessageDialog(null, pesan);
    }
    
    public void showMessage(String pesan, String judul, int jenisMessage) {
        JOptionPane.showMessageDialog(null, pesan, judul, jenisMessage);
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatDosen;
    private javax.swing.JTextField AlamatMahasiswa;
    private javax.swing.JButton BackViewDaftarKelas;
    private javax.swing.JButton CancelCreateAkunDosen;
    private javax.swing.JButton CancelCreateAkunMahasiswa;
    private javax.swing.JButton CancelDeleteMahasiswa;
    private javax.swing.JButton CancelJoinKelas;
    private javax.swing.JButton CancelKelas;
    private javax.swing.JButton CancelTugas;
    private javax.swing.JButton CreateAkunDosen;
    private javax.swing.JButton CreateAkunMahasiswa;
    private javax.swing.JButton CreateKelas;
    private javax.swing.JButton CreateTugas;
    private javax.swing.JTextField DeadlineTugas;
    private javax.swing.JButton DeleteMahasiswa;
    private javax.swing.JPasswordField FieldPassword;
    private javax.swing.JTextField FieldUsername;
    private javax.swing.JPanel HalamanAddMahasiswa;
    private javax.swing.JPanel HalamanCreateKelas;
    private javax.swing.JPanel HalamanCreateTugas;
    private javax.swing.JPanel HalamanDeleteMahasiswa;
    private javax.swing.JPanel HalamanJoinKelas;
    private javax.swing.JPanel HalamanLogin;
    private javax.swing.JPanel HalamanSignUpAs;
    private javax.swing.JPanel HalamanSignUpDosen;
    private javax.swing.JPanel HalamanSignUpMahasiswa;
    private javax.swing.JPanel HalamanViewDaftarKelas;
    private javax.swing.JButton JoinKelas;
    private javax.swing.JButton JoinKelasMenuMahasiswa;
    private javax.swing.JTextField KodeDosen;
    private javax.swing.JButton LihatDaftarKelas;
    private javax.swing.JList<String> ListDaftarKelas;
    private javax.swing.JComboBox<String> ListKelasJoinKelas;
    private javax.swing.JComboBox<String> ListNamaDosen;
    private javax.swing.JScrollPane ListNamaKelas;
    private javax.swing.JButton LogoutDosen;
    private javax.swing.JButton LogoutMahasiswa;
    private javax.swing.JPanel MenuDosen;
    private javax.swing.JPanel MenuMahasiswa;
    private javax.swing.JTextField NIMMahasiswa;
    private javax.swing.JTextField NIPDosen;
    private javax.swing.JTextField NamaDosen;
    private javax.swing.JTextField NamaKelas;
    private javax.swing.JTextField NamaMahasiswa;
    private javax.swing.JTextField NamaMatkul;
    private javax.swing.JTextField NamaTugas;
    private javax.swing.JPasswordField PasswordAkunDosen;
    private javax.swing.JPasswordField PasswordAkunMahasiswa;
    private javax.swing.JComboBox<String> PilihKelas;
    private javax.swing.JComboBox<String> PilihKelasDeleteMahasiswa;
    private javax.swing.JComboBox<String> PilihMahasiswaDeleteMahasiswa;
    private javax.swing.JComboBox<String> PilihNamaMatkul;
    private javax.swing.JButton SignIn;
    private javax.swing.JButton SignUp;
    private javax.swing.JButton SignUpDosen;
    private javax.swing.JButton SignUpMahasiswa;
    private javax.swing.JTextField UmurDosen;
    private javax.swing.JTextField UmurMahasiswa;
    private javax.swing.JTextField UsernameDosen;
    private javax.swing.JTextField UsernameMahasiswa;
    private javax.swing.JButton addMahasiswa;
    private javax.swing.JButton addMahasiswaKeKelas;
    private javax.swing.JTextField addNamaMahasiswa;
    private javax.swing.JTextField addNimMahasiswa;
    private javax.swing.JButton cancelMahasiswaKeKelas;
    private javax.swing.JButton createKelas;
    private javax.swing.JButton createTugas;
    private javax.swing.JPanel dasar;
    private javax.swing.JButton deletMahasiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
